# Generated by Django 4.0.4 on 2022-06-12 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_categoria_options_alter_fornecedor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='fornecedor',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='core.fornecedor'),
        ),
    ]
